<?php

include_once("basedatos.php");
class backup extends database_connect{

    function backup(){

        $dbName = 'proyecto';

        $laragonPath = realpath(__DIR__ . '/../../../..');

        // 2. Append the path to the executable relative to the Laragon root
        // NOTE: Use forward slashes (/) for better cross-platform compatibility
        $mysqlVersion = 'mysql-8.0.30-winx64'; // !! You'll need to update this version number !!
        $mysqlDumpRelativePath = "\\bin\\mysql\\$mysqlVersion\\bin\\mysqldump.exe";
        $mysqlDumpPath = $laragonPath . $mysqlDumpRelativePath;

        // 3. Define the backup destination (e.g., in a folder named 'backups' in your project)
        $backupDir = $laragonPath . '\\www\\SGHD-VES\\backups\\'; 
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0777, true);
        }

        $timestamp = date('Ymd_His');
        $backupFile = $backupDir . "\\" . $dbName . '_' . $timestamp . '.sql';
        $dbUser = 'root';
        $dbPass = '';

        // 4. Construct the executable command using absolute paths generated by PHP
        $command = "\"$mysqlDumpPath\" -u $dbUser --password=\"$dbPass\" $dbName > \"$backupFile\" 2>&1";

        // Execute the command
        exec($command, $output, $returnCode);

        return[
            'command' => $backupDir,
            'code' => $returnCode,
            'output' => $output
        ];
    }

    private function getBackupDirectory() {
        // Assuming your fix works: 3 levels up to the Laragon root
        $laragonPath = realpath(__DIR__ . '/../../..'); 
        
        // Define the backup destination path
        return $laragonPath . DIRECTORY_SEPARATOR . 'backups';
    }


    public function listBackups() {
        $backupDir = $this->getBackupDirectory();
        $backupFiles = [];
        
        // Check if the directory exists before trying to read it
        if (!is_dir($backupDir)) {
            return [];
        }

        // scandir returns all files/directories in the path
        $files = scandir($backupDir);

        foreach ($files as $file) {
            // 1. Check if the file name ends with .sql
            // 2. Ignore . and .. directories
            if (preg_match('/\.sql$/i', $file)) {
                $filePath = $backupDir . DIRECTORY_SEPARATOR . $file;
                
                $backupFiles[] = [
                    'name' => $file,
                    'path' => $filePath,
                    // Get the last modification time (timestamp)
                    'timestamp' => filemtime($filePath) 
                ];
            }
        }
        
        // Sort the array by timestamp (descending, newest first)
        usort($backupFiles, function($a, $b) {
            return $b['timestamp'] - $a['timestamp'];
        });

        // Return only the top 10 files
        return array_slice($backupFiles, 0, 10);
    }

}
/*

    */
?>